### PR TITLE
Fixed #40: Add ability to declare routines and triggers in export.

### LINKED ISSUE #40: Support --routine
Magento has stored routines for partial indexing. We need to add support for the ```--routine``` flag with n98-magerun. See https://github.com/netz98/n98-magerun/issues/529

### PR DESCRIPTION
**Pull request by bobbyshaw**

### CODE REVIEW

**Review by adam-paterson — APPROVED** [review]
Looks good to me

**Comment by bobbyshaw** [comment]
Cool. I forgot to ask. Do you have a database backup I can manually test this branch again? And what I'm looking out for still being in the export?

**Comment by adam-paterson** [comment]
@bobbyshaw Any 1.13+ EE database will do. And you'll need to check the catalog tables to see if they have triggers on them to add increments to the `_cl` tables.

**Comment by bobbyshaw** [comment]
Tested and it worked \o/. Merging

**Pull request merged**
